# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: ["**"]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  DevContainer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build docker images
        run: docker build -t local -f .devcontainer/Dockerfile .
      # - name: Login to conan
      # - name: Create conan packages
      #   run: conan create . 1.12.1@gtest/stable
      # - name: Upload conan packages
      #   run: conan upload "*" --all -r=default-conan-local -c
